modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      fail_if_not_ssl: false
      ip_protocol_fallback: false
      method: GET
      no_follow_redirects: false
      preferred_ip_protocol: "ipv4"
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
