name: Build Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.2'
    - uses: docker-practice/actions-setup-docker@master
    - name: Run docker tests
      run: cd tests && go test ./...
