name: Build Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.2'
    - uses: docker-practice/actions-setup-docker@master
    - name: Build docker image
      run: ./dockerize.sh
    - name: Run docker tests
      run: cd tests && go test ./...
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: nivaldogmelo/comment-api
        tags: v1, latest
        registry: docker.io
        dockerfile: build/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
