name: Fire up Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.9

    - name: Terraform fmt
      id: fmt
      working-directory: deploy/terraform
      run: terraform fmt -check
      continue-on-error: false

    - name: Terraform Init
      id: init
      working-directory: deploy/terraform
      run: terraform init

    - name: Terraform Validate
      id: validate
      working-directory: deploy/terraform
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      working-directory: deploy/terraform
      run: terraform plan -no-color
      continue-on-error: false

    - name: Terraform Apply
      id: apply
      working-directory: deploy/terraform
      run: terraform apply -auto-approve
      continue-on-error: false
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_TOKEN }}

    - name: Setup server IP
      run: sed "s/@IP/${{ steps.apply.outputs.stdout }} | grep \"ip\" | cut -d '\"' -f2/g deploy/ansible/hosts.yaml"

    - uses: saubermacherag/ansible-playbook-docker-action@v1.4
      with:
        playbookName: 'deploy/ansible/install_application/playbook.yaml'
        inventoryFile: 'deploy/ansible/hosts.yaml'
        keyFile: ${{ secrets.ANSIBLE_SSH_KEY }}
